src/classifier.jl, src/core.jl, src/image.jl, src/regressor.jl, test/core.jl
Changes include:
1. Remove batch_size from fit!
2. Changed `collate(model, X, y, batch_size)` to `collate(model, X, y)`, since batch_size should be inferred from `model.batch_size`. (adding batch_size explicitly to collate was kind of redundant)
=> Remove redundant args

README.md, src/classifier.jl, src/core.jl, src/image.jl, src/regressor.jl, test/core.jl, test/image.jl
=> Replace fit by build

.travis.yml, Project.toml, src/classifier.jl, src/core.jl, src/image.jl, src/regressor.jl, test/core.jl, test/regressor.jl
This PR is a continuation of #43 which:
- removes all `testmode!` toggling, leaving `Dropout` layers to be in `:auto` state by default (see https://github.com/FluxML/Flux.jl/blob/7a32a703f0f2842dda73d4454aff5990ade365d5/src/functor.jl#L42-L55). 
- modify/add tests to ensure that: 
- chains with `Dropout` layers are deterministic (inactive) when called on data before and after `fit`
- training with dropout layers with `p < 1` gives different outcome than training with `p=1` when initial weights are identical (the assumption being this implies the layers are stochastic (active) during training).
=> Address dropout in post zygote revision

test/image.jl
Our first GPU test is failing because the GPU and CPU are not giving final losses within tolerance of 0.0001, in the case of images. 
In this PR the tolerance is relaxed by one order of magnitude, which is probably still acceptable. 
I am not currently able to test locally, so this is "suck-it-and-see" PR.
=> Tests: relax tolerance for gpu/cpu agreement in image case

src/classifier.jl, src/core.jl, src/image.jl, src/regressor.jl, test/classifier.jl, test/image.jl, test/regressor.jl, test/test_utils.jl
This PR corrects an issue whereby optimiser "state" (eg, the momentum) is not carried over in a warm-restart. For example, the following test (added in this PR) now passes:
```julia
using MLJBase, MLJFlux
X, y = make_regression()
model = NeuralNetworkRegressor() 
model.epochs = 1
mach = machine(model, $X, $y);
Random.seed!(123)
fit!(mach, verbosity=0);
model.epochs = model.epochs + 1
fit!(mach, verbosity=0);
l1 = MLJBase.report(mach).training_losses[end]
Random.seed!(123)
fit!(mach, verbosity=1, force=true)
l2 = MLJBase.report(mach).training_losses[end]
@test l1 ≈ l2
```
=> Carry over optimiser state in update() methods

src/classifier.jl, src/core.jl, src/regressor.jl
This PR solves #142.
The BatchNorm layers (and perhaps other non-standard Flux layers) do not accept vector-shape data. Instead, they require matrices.
However, during prediction, the predict function of both NeuralNetworkClassifier and NeuralNetworkRegressor send data sample by sample to the network, in the form of vectors, causing an error.
The fix consists in reshaping the vector of length n into a matrix of shape n * 1.
=> Fix predict functions of models using BatchNorm

src/regressor.jl
The following
```julia
Model = @load MultitargetNeuralNetworkRegressor pkg=MLJFlux verbosity=0
```
> MLJFlux.NeuralNetworkRegressor
would load a basic `NeuralNetworkRegressor`.
=> Correclty load MultitargetNeuralNetworkRegressor

Project.toml, README.md, src/MLJFlux.jl, src/builders.jl, src/classifier.jl, src/common.jl, src/image.jl, src/regressor.jl, src/types.jl, test/builders.jl, test/image.jl, test/runtests.jl, test/test_utils.jl
=> Add interface point for RNGs

src/core.jl, test/builders.jl
Also removes some duplication in the computation of the training loss at each epoch.
=> Fix faulty test leading to "scalar indexing issue" on GPU builds

README.md, src/builders.jl, test/builders.jl
When prototyping, I would prefer not to have to write explicitly a new builder for any architecture I want to try.
=> Automate creation of new builders with @build

.github/workflows/ci.yml, src/core.jl
Addresses #185. 
I'm getting a  20x improvement on the example posted there:
```julia
using MLJ
N = 10^4
y = rand([0,1], N);
x1 = Float32.(y .+ 1)
df =(y = y,
x1 = x1,
x2 = x1,
x3 = x1,
x4 = x1);
y, X = unpack(df, ==(:y), !=(:y); :y=>Multiclass{2});
CLS = @load NeuralNetworkClassifier
nnc = CLS(epochs = 1)
mach = machine(nnc, X, y)
fit!(mach)
julia> @time fit!(mach, force=true)
[ Info: Training Machine{NeuralNetworkClassifier{Short,…},…} @508.
2.072888 seconds (5.53 M allocations: 1.805 GiB, 8.77% gc time, 2.36% compilation time)
```
Also, no StackOverflow in case of N=1850786
=> Improve one-hot encoding performance 

src/MLJFlux.jl, src/core.jl, src/mlj_model_interface.jl, test/core.jl
**Suggestion**
This adds a minor change to two important private methods: `train!` and `fit!`. Dispatching these on the `model::MLJFlux.MLJFluxModel` would allow users/developers to implement custom training loops without changing the default behaviour for default models (`NeuralNetworkRegressor`, `NeuralNetworkClassiefier`, ...). 
**Example**
I'm using this branch in the development version of a new package I'm working on: [`JointEnergyModels.jl`](https://github.com/JuliaTrustworthyAI/JointEnergyModels.jl). That package is tailored to `Flux.jl` but the minimal changes suggested here have made it possible to make it compatible with `MLJFlux.jl` without much hassle:
- Add a `JointEnergyClassifier` constructor that subtypes `MLJFlux.MLJFluxProbabilistic` and mostly inherits methods and …
=> Dispatch fit! and train! on model for greater extensibility

src/classifier.jl, src/core.jl, src/regressor.jl, src/types.jl, test/classifier.jl, test/regressor.jl
=> Sorting out issue with calling predict on matrix

src/regressor.jl
The PR #219 allows matrices but the target  scitype was not updated.
=> Fix target scitype for multitarget regressor

src/mlj_model_interface.jl, test/mlj_model_interface.jl
When a model is constructed with batch_size=0 it passes the [clean!](https://github.com/FluxML/MLJFlux.jl/blob/bf410e18b8ac019db740942ef3976edbae6d56df/src/mlj_model_interface.jl#L25) method without warning and batch_size remains at value 0. However the [fit!](https://github.com/FluxML/MLJFlux.jl/blob/bf410e18b8ac019db740942ef3976edbae6d56df/src/mlj_model_interface.jl#L65) method attempts to [collate](https://github.com/FluxML/MLJFlux.jl/blob/bf410e18b8ac019db740942ef3976edbae6d56df/src/core.jl#L231) the data into batches which is not possible due to the Julia [partition](https://github.com/JuliaLang/julia/blob/147bdf428cd14c979202678127d1618e425912d6/base/iterators.jl#L1264) method (please find the method below) called in collate throwing an error when attempting to set n as 0.
```julia …
```
=> Off-by-one error in clean! method

.buildkite/pipeline.yml, Project.toml
=> For a 0.3.1 release

src/mlj_model_interface.jl, test/mlj_model_interface.jl
This PR adds a check to the `clean!` method that throw an error if user passes an `optimiser` to a model that subtypes `Flux.Optimise.AbstractOptimiser`. Only optimisers from Optimisers.jl are now supported, and the error message explains as much.
=> Add check that Flux optimiser is not being used

Project.toml, src/core.jl, src/encoders.jl, src/entity_embedding.jl, src/mlj_model_interface.jl, test/classifier.jl, test/core.jl, test/encoders.jl, test/entity_embedding.jl, test/mlj_model_interface.jl, test/regressor.jl, test/runtests.jl
This PR replaces #272 and the fix #274, resolving #275.
=> Force `Float32` as type presented to Flux chains

Project.toml, src/core.jl, src/mlj_model_interface.jl, test/core.jl, test/mlj_model_interface.jl, test/runtests.jl
This follows up on https://github.com/JuliaAI/MLJModels.jl/issues/565 and just adds a tiny step that automatically converts input to `Float32` before passing it to Flux.
I can't see why anyone would ever not want this, as the eltype of any neural net generated through MLJFlux will always be `Float32`, and any other input type will be converted to `Float32` anyways, but with a much bigger computational cost. So I didn't build in an option to disable this behaviour.
The reason to have this in MLJFlux in particular is that other machines such as `MLJModels.OneHotEncoder` output Float64 types.
I didn't look into https://github.com/FluxML/MLJFlux.jl/pull/267 in detail and it might make this redundant in some cases, but maybe not in all?
=> automatically convert input matrix to Float32

src/MLJFlux.jl, src/entity_embedding.jl, src/entity_embedding_utils.jl, src/mlj_embedder_interface.jl, src/types.jl, test/entity_embedding.jl
Add an interface for `EntityEmbedder` that can wrap any basic deep learning model in an unsupervised model.
```julia
using MLJFlux
using MLJ
using CategoricalArrays
N = 200
X = (;
Column1 = repeat(Float32[1.0, 2.0, 3.0, 4.0, 5.0], Int(N / 5)),
Column2 = categorical(repeat(['a', 'b', 'c', 'd', 'e'], Int(N / 5))),
Column3 = categorical(repeat(["b", "c", "d", "f", "f"], Int(N / 5)), ordered = true),
Column4 = repeat(Float32[1.0, 2.0, 3.0, 4.0, 5.0], Int(N / 5)),
Column5 = randn(Float32, N),
Column6 = categorical(
repeat(["group1", "group1", "group2", "group2", "group3"], Int(N / 5)),
),
)
y = categorical([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])           # Classification
NeuralNetworkClassifier = @load NeuralNetworkClassifier pkg=MLJFlux
clf = NeuralNetworkClassifier(embedding_dims=Dict(:Column2 => …
```
=> ⭐️ Entity embedder interface is here
