Project.toml
src/MLJFlux.jl
test/mlj.jl
test/runtests.jl

- add .travis.yml file
- split [deps] into genuine dependencies and test dependencies
- dump MLJ as a dependency of any kind (MLJBase should suffice now)
**Important.** I have not yet done any review of recent updates to check for correctness of the tests. Only trying to get what is there to actually run and pass on travis. 
@ayush-1506 Thanks for recent work on this repo! Assuming this PR is passing tests on travis, can you please review it and merge if happy with it. Please review the [compat] requirement for Flux to make sure it is appropriate:
```
[compat]
CategoricalArrays = "^0.7.3"
Flux = "^0.8.3"
LossFunctions = "^0.5"
MLJBase = "^0.10"
ProgressMeter = "^1.1"
Tables = "^0.2"
julia = "1"
```
When this is done, I will review recent updates and suggest next steps.

Add CI and clean up Project.toml to get CI working and tests passing

---

src/MLJFlux.jl
src/core.jl

Just a small change. While running an example I realized that maybe the average loss makes more sense than the sum of all losses while training. (Else if we have large dataset, loss would be very high). 
@ablaom Would love your take on this.

Average loss makes more sense

---

src/core.jl

Use testmode

---

README.md
src/classifier.jl
src/core.jl
src/image.jl
src/regressor.jl
test/classifier.jl
test/core.jl
test/regressor.jl
test/runtests.jl

This is a review of the regressor tests (/tests/regressor.jl). The main changes are:
- add more complete tests for update logic 
- use metaprogramming to combine the tests for the two regressors, to eliminate code duplication, and increase coverage in the case of plain NeuralNetworkRegressor
**Looking ahead.** 
- I expect we can combine testing of all models into the one `eval` loop currently in regressors.jl. 
- I think image.jl does not even have testing.

Code review, Part 2

---

Project.toml
src/MLJFlux.jl
src/classifier.jl
src/core.jl
src/image.jl
src/regressor.jl
test/core.jl
test/regressor.jl
test/runtests.jl
test/test_utils.jl

Review of classifier.jl. 
Mostly minor fixes and some refactoring of tests in preparation for adding tests to classifier.

Code review Part3

---

test/core.jl

Test dropout in Short

---

src/regressor.jl

Forgot to convert TrackedValues to Float32 in regressor.

Don't use tracked values here

---

src/image.jl
test/image.jl

This addresses the comments in #4.

Extra argument for imageclassifier fit method

---

src/classifier.jl
src/image.jl
src/regressor.jl
test/test_utils.jl

Implement fitted params

---

src/core.jl

This is preventing update of MLJ registry.

Fix supertype of Builder (should  not be subtype of Model)

---

Project.toml
src/MLJFlux.jl
src/classifier.jl
src/core.jl
src/image.jl
src/regressor.jl
test/core.jl

Add option to use GPU

---

src/MLJFlux.jl
src/classifier.jl
src/common.jl
src/core.jl
src/image.jl
src/regressor.jl
test/_gpu_benchmarking.jl
test/classifier.jl
test/common.jl
test/core.jl
test/image.jl
test/regressor.jl
test/runtests.jl
test/test_utils.jl

Same as #66 but with squashed commits

Add GPU support take 3

---

.github/workflows/CompatHelper.yml
Project.toml

extend MLJModelInterface  compat

For a 0.1.6 release

---

.buildkite/pipeline.yml
README.md

Set up Buildkite

---

.buildkite/pipeline.yml

Only run Buildkite (GPU CI) on PRs to master

---

src/common.jl

Add acceleration cleanup in clean!

---

paper/paper.bib

Was pointed out during reviews. @ablaom

Small typo in paper

---

Project.toml

Only needed for testing.
cc @ayush-1506

mv MLDatasets to [extras]

---

Project.toml

Additional Project tweak for release 0.1.14 suspended by General

---

Project.toml

Hopefully addresses a ProgressMeter [bug](https://github.com/timholy/ProgressMeter.jl/issues/209#issuecomment-851780327) that has been intermittently crashing builds.

Bump compat ProgressMeter = "1.7.1" and version = "0.1.15"

---

Project.toml

For a 0.1.15 release

---

.github/workflows/ci_nightly.yml

Make sure the nightly CI has a different workflow name (#149)

---

Project.toml
src/core.jl
test/core.jl
test/test_utils.jl

Fixes #152 
cc @Leonardbcm Could you review please?

Redefine `reformat` for `Continuous` vectors to address silent loss function bug

---

.github/workflows/ci.yml
Project.toml
src/core.jl

For a 0.2.4 release

---

.buildkite/pipeline.yml
.github/workflows/ci.yml
.github/workflows/ci_nightly.yml
Project.toml
README.md
src/builders.jl

For a 0.2.5 release

---

test/classifier.jl
test/core.jl
test/image.jl
test/regressor.jl
test/test_utils.jl

Also increase learning rate in an image test to get a test to pass that didn't after RNG changes. 
Resolves #195

Use StableRNGs more comprehensively. 

---

src/core.jl

Divide penalty by n_batches

---

Project.toml
src/MLJFlux.jl

For a 0.2.9 release

---

.github/workflows/ci.yml
.github/workflows/ci_nightly.yml

Related to https://github.com/FluxML/Flux.jl/issues/2170

Actions node 12 => node 16

---

docs/src/interface/Classification.md
docs/src/interface/Summary.md
src/MLJFlux.jl
src/classifier.jl
src/core.jl
src/types.jl
test/classifier.jl

Replaces #248 with conflicts resolved. 
To do:

Add binary classifier

---

docs/src/extended_examples/MNIST/notebook.jl
docs/src/extended_examples/spam_detection/notebook.jl
src/types.jl

Fix `l2` loss in `MultitargetNeuralNetworkRegressor` doctring 

---

.github/workflows/ci.yml
test/mlj_model_interface.jl

Fix failing test caused by new Julia release

---

src/mlj_embedder_interface.jl

code was copied from MLJTransforms leading to issue #298

Fix mlj_embedder_interface.jl

---

Project.toml
src/mlj_embedder_interface.jl
test/mlj_model_interface.jl

I have made some fixes to the tests to make them pass with Flux 0.16. I am sharing them in case they are useful.

Test fixes for Flux 0.16

---

test/encoders.jl

To close #275 after it was reopened.

Add a test on the consistency of types before and after encoding.
